name = "All The Better Mooks"
author = "KiingTeezy"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3ef5c17150c40bc0bc5949f7f14bb561dcab77f387a0b10bb9a55664cf4c465"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.109"
