// priority: -100
// All The Better Mooks - display-name overrides (English). Item IDs are untouched, so recipes,
// quests and worlds are unaffected. Loads after ATM's lang.js so these names win.
ClientEvents.lang('en_us', atbm => {
  atbm.add("block.allthecompressed.allthemodium_block_1x", "Block of Mookium 1x")
  atbm.add("block.allthecompressed.allthemodium_block_2x", "Block of Mookium 2x")
  atbm.add("block.allthecompressed.allthemodium_block_3x", "Block of Mookium 3x")
  atbm.add("block.allthecompressed.allthemodium_block_4x", "Block of Mookium 4x")
  atbm.add("block.allthecompressed.allthemodium_block_5x", "Block of Mookium 5x")
  atbm.add("block.allthecompressed.allthemodium_block_6x", "Block of Mookium 6x")
  atbm.add("block.allthecompressed.allthemodium_block_7x", "Block of Mookium 7x")
  atbm.add("block.allthecompressed.allthemodium_block_8x", "Block of Mookium 8x")
  atbm.add("block.allthecompressed.allthemodium_block_9x", "Block of Mookium 9x")
  atbm.add("block.allthecompressed.atm_star_block_1x", "Mook Star Block 1x")
  atbm.add("block.allthecompressed.atm_star_block_2x", "Mook Star Block 2x")
  atbm.add("block.allthecompressed.atm_star_block_3x", "Mook Star Block 3x")
  atbm.add("block.allthecompressed.atm_star_block_4x", "Mook Star Block 4x")
  atbm.add("block.allthecompressed.atm_star_block_5x", "Mook Star Block 5x")
  atbm.add("block.allthecompressed.atm_star_block_6x", "Mook Star Block 6x")
  atbm.add("block.allthecompressed.atm_star_block_7x", "Mook Star Block 7x")
  atbm.add("block.allthecompressed.atm_star_block_8x", "Mook Star Block 8x")
  atbm.add("block.allthecompressed.atm_star_block_9x", "Mook Star Block 9x")
  atbm.add("block.allthecompressed.raw_allthemodium_block_1x", "Block of Raw Mookium 1x")
  atbm.add("block.allthecompressed.raw_allthemodium_block_2x", "Block of Raw Mookium 2x")
  atbm.add("block.allthecompressed.raw_allthemodium_block_3x", "Block of Raw Mookium 3x")
  atbm.add("block.allthecompressed.raw_allthemodium_block_4x", "Block of Raw Mookium 4x")
  atbm.add("block.allthecompressed.raw_allthemodium_block_5x", "Block of Raw Mookium 5x")
  atbm.add("block.allthecompressed.raw_allthemodium_block_6x", "Block of Raw Mookium 6x")
  atbm.add("block.allthecompressed.raw_allthemodium_block_7x", "Block of Raw Mookium 7x")
  atbm.add("block.allthecompressed.raw_allthemodium_block_8x", "Block of Raw Mookium 8x")
  atbm.add("block.allthecompressed.raw_allthemodium_block_9x", "Block of Raw Mookium 9x")
  atbm.add("block.allthecompressed.unobtainium_allthemodium_block_1x", "Block of Unobtainium - Mookium Alloy 1x")
  atbm.add("block.allthecompressed.unobtainium_allthemodium_block_2x", "Block of Unobtainium - Mookium Alloy 2x")
  atbm.add("block.allthecompressed.unobtainium_allthemodium_block_3x", "Block of Unobtainium - Mookium Alloy 3x")
  atbm.add("block.allthecompressed.unobtainium_allthemodium_block_4x", "Block of Unobtainium - Mookium Alloy 4x")
  atbm.add("block.allthecompressed.unobtainium_allthemodium_block_5x", "Block of Unobtainium - Mookium Alloy 5x")
  atbm.add("block.allthecompressed.unobtainium_allthemodium_block_6x", "Block of Unobtainium - Mookium Alloy 6x")
  atbm.add("block.allthecompressed.unobtainium_allthemodium_block_7x", "Block of Unobtainium - Mookium Alloy 7x")
  atbm.add("block.allthecompressed.unobtainium_allthemodium_block_8x", "Block of Unobtainium - Mookium Alloy 8x")
  atbm.add("block.allthecompressed.unobtainium_allthemodium_block_9x", "Block of Unobtainium - Mookium Alloy 9x")
  atbm.add("block.allthecompressed.vibranium_allthemodium_block_1x", "Block of Vibranium - Mookium Alloy 1x")
  atbm.add("block.allthecompressed.vibranium_allthemodium_block_2x", "Block of Vibranium - Mookium Alloy 2x")
  atbm.add("block.allthecompressed.vibranium_allthemodium_block_3x", "Block of Vibranium - Mookium Alloy 3x")
  atbm.add("block.allthecompressed.vibranium_allthemodium_block_4x", "Block of Vibranium - Mookium Alloy 4x")
  atbm.add("block.allthecompressed.vibranium_allthemodium_block_5x", "Block of Vibranium - Mookium Alloy 5x")
  atbm.add("block.allthecompressed.vibranium_allthemodium_block_6x", "Block of Vibranium - Mookium Alloy 6x")
  atbm.add("block.allthecompressed.vibranium_allthemodium_block_7x", "Block of Vibranium - Mookium Alloy 7x")
  atbm.add("block.allthecompressed.vibranium_allthemodium_block_8x", "Block of Vibranium - Mookium Alloy 8x")
  atbm.add("block.allthecompressed.vibranium_allthemodium_block_9x", "Block of Vibranium - Mookium Alloy 9x")
  atbm.add("block.allthemodium.allthemodium_block", "Block of Mookium")
  atbm.add("block.allthemodium.allthemodium_ore", "Mookium Ore")
  atbm.add("block.allthemodium.deepslate_allthemodium_ore", "Deepslate Mookium Ore")
  atbm.add("block.allthemodium.molten_allthemodium", "Molten Mookium")
  atbm.add("block.allthemodium.raw_allthemodium_block", "Block of Raw Mookium")
  atbm.add("block.allthemodium.unobtainium_allthemodium_block", "Block of Unobtainium - Mookium Alloy")
  atbm.add("block.allthemodium.vibranium_allthemodium_block", "Block of Vibranium - Mookium Alloy")
  atbm.add("block.allthetweaks.atm_star_block", "Mook Star Block")
  atbm.add("block.allthetweaks.trophy_atm", "Better Mooks Trophy")
  atbm.add("block.geore.allthemodium_block", "Block Of Mookium GeOre")
  atbm.add("block.geore.allthemodium_cluster", "Mookium GeOre Cluster")
  atbm.add("block.geore.allthemodium_tinted_glass", "Mookium Tinted Glass")
  atbm.add("block.geore.budding_allthemodium", "Budding Mookium GeOre")
  atbm.add("block.geore.large_allthemodium_bud", "Large Mookium GeOre Bud")
  atbm.add("block.geore.medium_allthemodium_bud", "Medium Mookium GeOre Bud")
  atbm.add("block.geore.small_allthemodium_bud", "Small Mookium GeOre Bud")
  atbm.add("block.ironfurnaces.allthemodium_furnace", "Mookium Furnace")
  atbm.add("container.ironfurnaces.allthemodium_furnace", "Mookium Furnace")
  atbm.add("creative_tab.allthemodium.default_tab", "Mookium")
  atbm.add("entity.allthemodium.alloy_trident", "Mookium Alloy Trident")
  atbm.add("entity.productivebees.allthemodium_bee", "Mookium Bee")
  atbm.add("geore.configuration.generateAllthemodiumGeore", "Generate Mookium GeOre")
  atbm.add("geore.configuration.generateAllthemodiumGeore.tooltip", "Generate Mookium GeOre [Default: false]")
  atbm.add("item.allthemodium.alloy_axe", "Mookium Alloy Axe")
  atbm.add("item.allthemodium.alloy_mace", "Mookium Alloy Mace")
  atbm.add("item.allthemodium.alloy_paxel", "Mookium Alloy Paxel")
  atbm.add("item.allthemodium.alloy_shovel", "Mookium Alloy Shovel")
  atbm.add("item.allthemodium.alloy_sword", "Mookium Alloy Sword")
  atbm.add("item.allthemodium.alloy_trident", "Mookium Alloy Trident")
  atbm.add("item.allthemodium.allthemodium_apple", "Mookium Apple")
  atbm.add("item.allthemodium.allthemodium_axe", "Mookium Axe")
  atbm.add("item.allthemodium.allthemodium_boots", "Mookium Boots")
  atbm.add("item.allthemodium.allthemodium_bow", "Mookium Bow")
  atbm.add("item.allthemodium.allthemodium_carrot", "Mookium Carrot")
  atbm.add("item.allthemodium.allthemodium_chestplate", "Mookium Chestplate")
  atbm.add("item.allthemodium.allthemodium_dust", "Mookium Dust")
  atbm.add("item.allthemodium.allthemodium_gear", "Mookium Gear")
  atbm.add("item.allthemodium.allthemodium_helmet", "Mookium Helmet")
  atbm.add("item.allthemodium.allthemodium_hoe", "Mookium Hoe")
  atbm.add("item.allthemodium.allthemodium_ingot", "Mookium Ingot")
  atbm.add("item.allthemodium.allthemodium_leggings", "Mookium Leggings")
  atbm.add("item.allthemodium.allthemodium_mace", "Mookium Mace")
  atbm.add("item.allthemodium.allthemodium_nugget", "Mookium Nugget")
  atbm.add("item.allthemodium.allthemodium_pickaxe", "Mookium Pickaxe")
  atbm.add("item.allthemodium.allthemodium_plate", "Mookium Plate")
  atbm.add("item.allthemodium.allthemodium_rod", "Mookium Rod")
  atbm.add("item.allthemodium.allthemodium_shovel", "Mookium Shovel")
  atbm.add("item.allthemodium.allthemodium_sword", "Mookium Sword")
  atbm.add("item.allthemodium.allthemodium_upgrade_smithing_template", "Mookium Smithing Template")
  atbm.add("item.allthemodium.molten_allthemodium_bucket", "Molten Mookium Bucket")
  atbm.add("item.allthemodium.raw_allthemodium", "Raw Mookium Ore")
  atbm.add("item.allthemodium.unobtainium_allthemodium_alloy_dust", "Unobtainium - Mookium Alloy Dust")
  atbm.add("item.allthemodium.unobtainium_allthemodium_alloy_ingot", "Unobtainium - Mookium Alloy Ingot")
  atbm.add("item.allthemodium.vibranium_allthemodium_alloy_dust", "Vibranium - Mookium Alloy Dust")
  atbm.add("item.allthemodium.vibranium_allthemodium_alloy_ingot", "Vibranium - Mookium Alloy Ingot")
  atbm.add("item.allthetweaks.atm_star", "Mook Star")
  atbm.add("item.allthetweaks.atm_star_shard", "Mook Star Shard")
  atbm.add("item.geore.allthemodium_shard", "Mookium GeOre Shard")
  atbm.add("item.geore.allthemodium_spyglass", "Mookium GeOre Spyglass")
  atbm.add("item.ironfurnaces.allthemodium_furnace", "Mookium Furnace")
  atbm.add("item.ironfurnaces.upgrade_allthemodium", "Netherite to Mookium Furnace Upgrade")
  atbm.add("item.ironfurnaces.upgrade_vibranium", "Mookium to Vibranium Furnace Upgrade")
  atbm.add("item.kubejs.atm_star_shard_1", "Mook Star Fragment")
  atbm.add("item.kubejs.atm_star_shard_2", "Mook Star Fragment")
  atbm.add("item.kubejs.atm_star_shard_3", "Mook Star Fragment")
  atbm.add("item.kubejs.atm_star_shard_4", "Mook Star Fragment")
  atbm.add("item.kubejs.atm_star_shard_5", "Mook Star Fragment")
  atbm.add("item.kubejs.silent_allthemodium_plate", "Silent Mookium Plate")
  atbm.add("item.productivebees.honeycomb_allthemodium", "Mookium Comb")
  atbm.add("item.theurgy.alchemical_sulfur_allthemodium.source", "Mookium")
  atbm.add("material.irons_jewelry.allthemodium", "Mookium")
  atbm.add("trim_material.allthemodium.allthemodium", "Mookium")
  atbm.add("upgrade.allthemodium.allthemodium_upgrade", "Mookium Upgrade")
})
